// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';

/**
 * Horizon Stays docs site.
 *
 * Generated pages (Home, All components, component pages, Tokens, Changelog,
 * Roadmap, News) come from scripts/generate.mjs, run at a pinned commit of
 * main. Every other page is a written guide under src/content/docs/.
 *
 * The sidebar is written out entry by entry, never autogenerated: Starlight
 * fails the build when a slug has no page, so a page that failed to generate
 * breaks the build instead of quietly vanishing from the navigation. The
 * component entries between the generated:components markers are rewritten by
 * the generator from the eligible list; everything else here is hand-kept.
 *
 * starlight-links-validator makes a broken internal link fail the build.
 */
export default defineConfig({
  site: 'https://horizon-stays-docs.vercel.app',
  integrations: [
    starlight({
      title: 'Horizon Stays',
      description: 'Reference for the Horizon Stays design system.',
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/Aye-Kyawt/horizon-stays-design-system' }],
      plugins: [starlightLinksValidator({ errorOnFallbackPages: false })],
      customCss: [
        '@fontsource/inter/400.css',
        '@fontsource/inter/500.css',
        '@fontsource/inter/600.css',
        '@fontsource/inter/700.css',
        '@fontsource/padauk/400.css',
        '@fontsource/padauk/700.css',
        './src/styles/tokens.css',
        './src/styles/custom.css',
      ],
      components: {
        Footer: './src/components/Footer.astro',
      },
      sidebar: [
        {
          label: 'Get Started',
          items: [
            { label: 'Changelog', slug: 'get-started/changelog' },
            { label: 'Roadmap', slug: 'get-started/roadmap' },
            { label: 'News', slug: 'get-started/news' },
            { label: 'Versioning', slug: 'get-started/versioning' },
            { label: 'Upgrading', slug: 'get-started/upgrading' },
          ],
        },
        {
          label: 'Designing',
          items: [{ label: 'Introduction', slug: 'designing/introduction' }],
        },
        {
          label: 'Developing',
          items: [
            { label: 'Introduction', slug: 'developing/introduction' },
            { label: 'React', slug: 'developing/react' },
            { label: 'React Router', slug: 'developing/react-router' },
          ],
        },
        {
          label: 'Skills',
          items: [{ label: 'Knowledge skill', slug: 'skills/knowledge-skill' }],
        },
        {
          label: 'Core',
          items: [
            {
              label: 'Components',
              items: [
                { label: 'All components', slug: 'core/components/overview' },
                // <generated:components>
              { label: 'Button', slug: 'core/components/button' },
              { label: 'cardText', slug: 'core/components/cardtext' },
              // </generated:components>
              ],
            },
            { label: 'Tokens', slug: 'core/tokens' },
          ],
        },
        {
          label: 'Styling',
          items: [{ label: 'Theming', slug: 'styling/theming' }],
        },
        {
          label: 'Help',
          items: [
            { label: 'FAQ', slug: 'help/faq' },
            { label: 'Report a bug', slug: 'help/bug-report' },
            { label: 'Request a feature', slug: 'help/feature-request' },
            { label: 'Contributing', slug: 'help/contributing' },
            { label: 'Embedding', slug: 'help/embedding' },
          ],
        },
      ],
    }),
  ],
});
