/**
 * Horizon Stays Design System — registry ID resolver
 *
 * Writes `.claude/registry.local.json` by resolving every NAME in
 * `.claude/registry.local.example.json` to its real Airtable ID.
 *
 * The example file is the committed contract of names: which tables the
 * registry has, and which columns each one carries. It holds no IDs, and it
 * must not — the repo is public, and the registry contract keeps IDs in
 * exactly one gitignored place so a renamed or rebuilt base is a one-file fix.
 *
 * This script is what makes that split survivable. A fresh clone runs
 *
 *   AIRTABLE_PAT=pat... npm run registry:init
 *
 * and gets real IDs without a single one passing through git.
 *
 * Needs a personal access token with the `schema.bases:read` scope, and access
 * to the base named in the example file's `baseName`. Create one at
 * https://airtable.com/create/tokens
 *
 * Uses the Airtable metadata API over global fetch. No new dependency —
 * tools.md asks for a reason before adding one, and there isn't one here.
 */

import fs from 'node:fs';
import path from 'node:path';

const EXAMPLE = path.join('.claude', 'registry.local.example.json');
const OUT = path.join('.claude', 'registry.local.json');
const API = 'https://api.airtable.com/v0/meta';

const TOKEN =
  process.env.AIRTABLE_PAT ||
  process.env.AIRTABLE_API_KEY ||
  process.env.AIRTABLE_TOKEN;

const force = process.argv.includes('--force');

/** Stop with a readable message rather than a stack trace. */
function fail(message, hint) {
  console.error(`\nregistry:init — ${message}`);
  if (hint) console.error(`\n${hint}`);
  console.error('');
  process.exit(1);
}

async function api(url) {
  const res = await fetch(url, { headers: { Authorization: `Bearer ${TOKEN}` } });
  if (res.status === 401) {
    fail('Airtable rejected the token (401).', 'Check the value, and that it has not been revoked.');
  }
  if (res.status === 403) {
    fail(
      'The token is valid but not allowed to read schema (403).',
      'It needs the `schema.bases:read` scope, and the base must be in its access list.',
    );
  }
  if (!res.ok) {
    fail(`Airtable returned ${res.status} for ${url}`, await res.text().catch(() => ''));
  }
  return res.json();
}

/** The metadata API pages with an `offset` cursor. */
async function listBases() {
  const bases = [];
  let offset;
  do {
    const url = offset ? `${API}/bases?offset=${encodeURIComponent(offset)}` : `${API}/bases`;
    const page = await api(url);
    bases.push(...(page.bases ?? []));
    offset = page.offset;
  } while (offset);
  return bases;
}

if (!TOKEN) {
  fail(
    'No Airtable token in the environment.',
    'Set AIRTABLE_PAT (or AIRTABLE_API_KEY) to a personal access token with the\n' +
      '`schema.bases:read` scope, then run again:\n\n' +
      '  AIRTABLE_PAT=pat... npm run registry:init\n\n' +
      'Create one at https://airtable.com/create/tokens — do not commit it.',
  );
}

if (!fs.existsSync(EXAMPLE)) {
  fail(`${EXAMPLE} is missing.`, 'It is the list of names this script resolves; restore it from git.');
}

if (fs.existsSync(OUT) && !force) {
  fail(
    `${OUT} already exists.`,
    'Re-run with --force to overwrite it:\n\n  npm run registry:init -- --force',
  );
}

const template = JSON.parse(fs.readFileSync(EXAMPLE, 'utf8'));
const baseName = template.baseName;

if (!baseName) {
  fail(`${EXAMPLE} has no "baseName".`, 'The script resolves the base by name, so that field is required.');
}

console.log(`\nregistry:init — resolving "${baseName}"\n`);

const bases = await listBases();
const matches = bases.filter((b) => b.name === baseName);

if (matches.length === 0) {
  const names = bases.map((b) => `  · ${b.name}`).join('\n');
  fail(
    `No base named "${baseName}" is visible to this token.`,
    names ? `Bases the token can see:\n${names}` : 'The token can see no bases at all.',
  );
}
if (matches.length > 1) {
  fail(
    `${matches.length} bases are named "${baseName}".`,
    'Rename one, or narrow the token to the base you mean — the script will not guess.',
  );
}

const base = matches[0];
const schema = await api(`${API}/bases/${base.id}/tables`);
const tablesByName = new Map(schema.tables.map((t) => [t.name, t]));

const out = {
  _comment:
    'Local, gitignored. The only place Airtable IDs for the Horizon Stays registry are written down. ' +
    'Generated by `npm run registry:init` from the names in .claude/registry.local.example.json — ' +
    're-run it rather than editing by hand, and never paste an ID into a skill, an agent file, or a script.',
  baseId: base.id,
  baseName: base.name,
  baseUrl: `https://airtable.com/${base.id}`,
  tables: {},
};

const missingTables = [];
const missingFields = [];

for (const [tableName, spec] of Object.entries(template.tables ?? {})) {
  const table = tablesByName.get(tableName);
  if (!table) {
    missingTables.push(tableName);
    continue;
  }

  const fieldsByName = new Map(table.fields.map((f) => [f.name, f.id]));
  const fields = {};

  for (const fieldName of Object.keys(spec.fields ?? {})) {
    const id = fieldsByName.get(fieldName);
    if (!id) {
      missingFields.push(`${tableName} › ${fieldName}`);
      continue;
    }
    fields[fieldName] = id;
  }

  out.tables[tableName] = { id: table.id, fields };

  const want = Object.keys(spec.fields ?? {}).length;
  const got = Object.keys(fields).length;
  const extra = table.fields.length - got;
  console.log(
    `  ${got === want ? '✓' : '!'} ${tableName.padEnd(20)} ${String(got).padStart(2)}/${want} columns` +
      (extra > 0 ? `   (${extra} in Airtable not in the template)` : ''),
  );
}

if (missingTables.length || missingFields.length) {
  console.error('\nregistry:init — the base does not match the template.\n');
  for (const t of missingTables) console.error(`  missing table   ${t}`);
  for (const f of missingFields) console.error(`  missing column  ${f}`);
  console.error(
    '\nNothing was written. Either the base was renamed or rebuilt, or the template is stale.\n' +
      'Fix the names so the two agree — do not hand-write the IDs, that is the thing this avoids.\n',
  );
  process.exit(1);
}

fs.writeFileSync(OUT, `${JSON.stringify(out, null, 2)}\n`);

const tableCount = Object.keys(out.tables).length;
const fieldCount = Object.values(out.tables).reduce((n, t) => n + Object.keys(t.fields).length, 0);

console.log(`\n  wrote ${OUT}`);
console.log(`  ${tableCount} tables, ${fieldCount} columns, base ${out.baseId}`);
console.log('\n  This file is gitignored. Keep it that way.\n');
